version: '3.9'

services:
  test:
    image: ghcr.io/tastybamboo/panda-cms-test:local
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/panda_cms_dummy_test
      PGUSER: postgres
      PGPASSWORD: password
      PGHOST: postgres
      PGPORT: 5432
      RAILS_ENV: test
      CI: 'true'
      CUPRITE_TIMEOUT: 20
      CUPRITE_PROCESS_TIMEOUT: 40
    volumes:
      - ./:/app:delegated
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: >
      bash -lc "
        bundle install &&
        bundle exec rails db:create db:schema:load &&
        bundle exec rspec --format documentation --color
      "

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: panda_cms_dummy_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 3s
      retries: 8
